FROM registry.ci.openshift.org/ocp/4.20:base-rhel9

RUN set -e && dnf clean all && rm -rf /var/cache/dnf/* \
  && dnf update -y \
  && dnf install -y rust cargo libffi-devel python3.12-devel gcc \
  && pushd /usr/local/bin && ln -sf ../../bin/python3.12 python3 && popd \
  && python3 -m ensurepip --upgrade

COPY ./images/ansible-operator/Pipfile* ./

# The build dependencies are required by cachito. Following script
# does exactly the same. More info at: https://github.com/containerbuildsystem/cachito/blob/master/docs/pip.md#build-dependencies
RUN curl -LO https://raw.githubusercontent.com/containerbuildsystem/cachito/master/bin/pip_find_builddeps.py \
  && chmod +x pip_find_builddeps.py

RUN python3 -m pip install --upgrade pip

# Create requirements.in file from the pipenv created using the
# same Pipfile and Pipfile.lock used for upstream image. Then
# use pip-compile to generate the requirements.txt file.
RUN python3 -m pip install pipenv==2023.11.15 \
  && python3 -m pip install pip-tools \
  && pipenv install --deploy \
  # NOTE: This ignored vulnerability (71064) was detected in requests, \
  # but the upgraded version doesn't support the use case (protocol we are using).\
  # Ref: https://github.com/operator-framework/ansible-operator-plugins/pull/67#issuecomment-2189164688
  && pipenv check --ignore 71064 \
  && pipenv run pip freeze --all  > ./requirements.in \
  && pip-compile --output-file=./requirements.txt ./requirements.in --strip-extras \
  # NOTE: Comment out ansible-core, ansible-runner, ansible-runner-http, and
  # requests-unixsocket from `requirements.txt` to avoid running
  # `pip_find_builddeps.py` against these (setuptools/setuptools-scm conflicts).
  # kubernetes 35.x is left in; cryptography/cffi/pycparser/maturin are commented
  # for OSBS (installed via rpms).
  && sed -i '/ansible-core==/s/^/#/g' ./requirements.txt \
  && sed -i '/ansible-runner==/s/^/#/g' ./requirements.txt \
  && sed -i '/ansible-runner-http==/s/^/#/g' ./requirements.txt \
  && sed -i '/requests-unixsocket==/s/^/#/g' ./requirements.txt \
  # NOTE: Comment out cryptography and its dependencies from the requirements.txt
  # files as these packages can't be installed in the isolated environment of OSBS
  # image build. These packages will be installed through rpms.
  && sed -i '/cryptography==/s/^/#/g' ./requirements.txt \
  && sed -i '/cffi==/s/^/#/g' ./requirements.txt \
  && sed -i '/pycparser==/s/^/#/g' ./requirements.txt \
  && sed -i '/maturin==/s/^/#/g' ./requirements.txt \
  # Use --allow-binary so pip does not force build-from-source; without it we hit setuptools-scm
  # conflicts during resolution.
  && ./pip_find_builddeps.py requirements.txt -o requirements-build.in --append --allow-binary \
  # Uncomment the above packages so they are re-enabled in requirements.txt.
  && sed -i '/ansible-core==/s/^#//g' ./requirements.txt \
  && sed -i '/ansible-runner==/s/^#//g' ./requirements.txt \
  && sed -i '/ansible-runner-http==/s/^#//g' ./requirements.txt \
  && sed -i '/requests-unixsocket==/s/^#//g' ./requirements.txt \
  # Resolve setuptools-scm conflict: remove any setuptools-scm from build deps and pin >=8.
  && sed -i '/^setuptools-scm$/d' ./requirements-build.in \
  && sed -i '/^setuptools_scm$/d' ./requirements-build.in \
  && echo 'setuptools-scm>=8' >> ./requirements-build.in \
  && pip-compile --output-file=./requirements-build.txt ./requirements-build.in --strip-extras --allow-unsafe \
  # NOTE: Comment out cryptography and its dependencies from the requirements-build.txt
  # files as these packages can't be installed in the isolated environment of OSBS image
  # build. These packages will be installed through rpms.
  && sed -i '/cryptography==/s/^/#/g' ./requirements-build.txt \
  && sed -i '/cffi==/s/^/#/g' ./requirements-build.txt \
  && sed -i '/pycparser==/s/^/#/g' ./requirements-build.txt \
  && sed -i '/maturin==/s/^/#/g' ./requirements-build.txt \
  # Add ansible-core into a separate requirements-build1-temp.in file to include it
  # into the requirements-build1.in file.
  && grep "ansible-core==" ./requirements.in >> ./requirements-build1-temp.in || true \
  && ./pip_find_builddeps.py requirements-build1-temp.in -o requirements-build1.in --append \
  && (sed -i '/^setuptools-scm$/d' ./requirements-build1.in; sed -i '/^setuptools_scm$/d' ./requirements-build1.in; echo 'setuptools-scm>=8' >> ./requirements-build1.in) \
  && pip-compile --output-file=./requirements-build1.txt ./requirements-build1.in --strip-extras --allow-unsafe \
  # Pin wheel to 0.46.3+ for CVE-2026-24049 (requirements-build1 is installed after requirements-pre-build, so this wins).
  && sed -i 's/^wheel==[0-9.]*$/wheel==0.46.3/' ./requirements-build1.txt \
  # NOTE: Comment out cryptography and its dependencies from the requirements-build1.txt
  # files as these packages can't be installed in the isolated environment of OSBS
  # image build. These packages will be installed through rpms.
  && sed -i '/cryptography==/s/^/#/g' ./requirements-build1.txt \
  && sed -i '/cffi==/s/^/#/g' ./requirements-build1.txt \
  && sed -i '/pycparser==/s/^/#/g' ./requirements-build1.txt \
  && sed -i '/maturin==/s/^/#/g' ./requirements-build1.txt \
  # Add ansible-runner into a separate requirements-pre-build-temp.in
  # file to include it into the requirements-pre-build.in file.
  && grep "ansible-runner==" ./requirements.in >> ./requirements-pre-build-temp.in || true \
  # Add flit-core to requirements-pre-build.in file as this package is part of the
  # build dependencies of some packages in requirements-build.txt file.
  && grep "flit-core==" ./requirements-build.txt >> ./requirements-pre-build.in || true \
  && ./pip_find_builddeps.py requirements-pre-build-temp.in -o requirements-pre-build.in --append \
  && (sed -i '/^setuptools-scm$/d' ./requirements-pre-build.in; sed -i '/^setuptools_scm$/d' ./requirements-pre-build.in; echo 'setuptools-scm>=8' >> ./requirements-pre-build.in) \
  && pip-compile --output-file=./requirements-pre-build.txt ./requirements-pre-build.in --strip-extras --allow-unsafe \
  # So the Cachito bundle contains wheel 0.45.1 for PEP 517 isolated builds (e.g. ansible-core
  # requires wheel==0.45.1). requirements-build1.txt pins wheel==0.46.3 (CVE); install order
  # (pre-build then build1) leaves the main env on 0.46.3.
  && sed -i 's/^wheel==[0-9.]*$/wheel==0.45.1/' ./requirements-pre-build.txt

VOLUME /tmp/requirements
ENTRYPOINT ["cp", "./requirements.txt", "./requirements-build.txt",  "./requirements-build1.txt", "./requirements-pre-build.txt", "/tmp/requirements/"]
